services:
  postgres:
    image: postgres:latest
    container_name: diceFactoryDB
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwertyuiop
    ports:
      - "5050:5432"
    restart: always

  spring-boot:
    build: .
    ports:
      - "8080:8080"
    container_name: spring-boot
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwertyuiop


