spring.application.name=spring
spring.datasource.url=jdbc:postgresql://localhost:5432/dicefactory
spring.datasource.username=postgres
spring.datasource.password=qwertyuiop
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true